import type { CategoryKey, WordUnit } from './types'

export const CATEGORY_LABELS: Record<CategoryKey, string> = {
  shape: '基础形状',
  food: '食物',
  animal: '动物',
  nature: '自然界',
  object: '交通与物品',
}

export const WORDS: WordUnit[] = [
  // shape 1-20
  { id: 1, emoji: '☀️', pinyin: 'tài yáng', hanzi: '太阳', english: 'sun', category: 'shape', teaser: '太阳好温暖!咦…晚上天上那个亮亮的是什么?' },
  { id: 2, emoji: '🌙', pinyin: 'yuè liang', hanzi: '月亮', english: 'moon', category: 'shape', teaser: '月亮姐姐眨眨眼,身边怎么藏着一群一闪一闪的小眼睛…是谁呀?' },
  { id: 3, emoji: '⭐', pinyin: 'xīng xing', hanzi: '星星', english: 'star', category: 'shape', teaser: '数一数星星,咦,有几颗躲到白白的棉花团后头啦?' },
  { id: 4, emoji: '☁️', pinyin: 'yún', hanzi: '云', english: 'cloud', category: 'shape', teaser: '白白云朵圆滚滚,好像能拍一拍、踢一踢…会是什么呀?' },
  { id: 5, emoji: '⚽', pinyin: 'qiú', hanzi: '球', english: 'ball', category: 'shape', teaser: '圆球滚呀滚,滚到一位装满故事、方方正正的好朋友身边…它是谁?' },
  { id: 6, emoji: '📖', pinyin: 'shū', hanzi: '书', english: 'book', category: 'shape', teaser: '故事书讲到一半,咦,一扇神秘的入口正等着你推开…里面有什么?' },
  { id: 7, emoji: '🚪', pinyin: 'mén', hanzi: '门', english: 'door', category: 'shape', teaser: '推开大门,墙上那双亮晶晶的玻璃眼睛也探头看外面…它是谁?' },
  { id: 8, emoji: '🪟', pinyin: 'chuāng hu', hanzi: '窗户', english: 'window', category: 'shape', teaser: '窗外天色变呀变,屋里墙上的滴答声提醒魔法时间到…是谁在走?' },
  { id: 9, emoji: '🕐', pinyin: 'zhōng', hanzi: '钟', english: 'clock', category: 'shape', teaser: '滴答滴答,下课啦!窗外天空飘着一只拖着长尾巴的彩色朋友…它在等谁?' },
  { id: 10, emoji: '🪁', pinyin: 'fēng zheng', hanzi: '风筝', english: 'kite', category: 'shape', teaser: '风筝飞上云朵边,低头一看,大地鼓起一个高高的绿色大背脊…那是什么?' },
  { id: 11, emoji: '⛰️', pinyin: 'shān', hanzi: '山', english: 'mountain', category: 'shape', teaser: '爬上高山,忽然飘来小雨点,头顶撑开一朵会挡雨的小蘑菇…是什么呢?' },
  { id: 12, emoji: '☂️', pinyin: 'yǔ sǎn', hanzi: '雨伞', english: 'umbrella', category: 'shape', teaser: '收起雨伞,雨停啦,该回那座最温暖、晚上会亮灯的小屋啦…是谁的家呀?' },
  { id: 13, emoji: '🏠', pinyin: 'fáng zi', hanzi: '房子', english: 'house', category: 'shape', teaser: '回到温暖的家门口,咦,口袋空空?开门需要一位会魔法的小帮手…它藏哪啦?' },
  { id: 14, emoji: '🔑', pinyin: 'yào shi', hanzi: '钥匙', english: 'key', category: 'shape', teaser: '用钥匙开开门,魔法师有点渴啦,桌上那个圆滚滚、装满热热好东西的朋友…是谁呀?' },
  { id: 15, emoji: '☕', pinyin: 'bēi zi', hanzi: '杯子', english: 'cup', category: 'shape', teaser: '捧着暖暖的杯子要出门啦!脑袋上还差一样软软挡风的好朋友…是什么呢?' },
  { id: 16, emoji: '🎩', pinyin: 'mào zi', hanzi: '帽子', english: 'hat', category: 'shape', teaser: '小帽子戴戴好,脚丫丫也想要暖暖的保护…一双会走路的好朋友是谁呀?' },
  { id: 17, emoji: '👟', pinyin: 'xié zi', hanzi: '鞋子', english: 'shoe', category: 'shape', teaser: '穿好小鞋子要出发啦!东西好多,背上那位大肚子好朋友帮你装…它是谁?' },
  { id: 18, emoji: '🎒', pinyin: 'bāo', hanzi: '包', english: 'bag', category: 'shape', teaser: '小书包回到家,天黑啦!书桌上那位一碰就亮起暖光、陪你读故事的朋友…是谁呀?' },
  { id: 19, emoji: '💡', pinyin: 'tái dēng', hanzi: '台灯', english: 'lamp', category: 'shape', teaser: '台灯亮起,咦,墙角躲着一个扎着蝴蝶结、想给你惊喜的大盒子…是什么呢?' },
  { id: 20, emoji: '🎁', pinyin: 'lǐ wù', hanzi: '礼物', english: 'gift', category: 'shape', teaser: '拆开礼物盒,里面跳出一颗红通通、咬一口嘎嘣脆的香甜果子…是谁呀?' },
  // food 21-40
  { id: 21, emoji: '🍎', pinyin: 'píng guǒ', hanzi: '苹果', english: 'apple', category: 'food', teaser: '苹果又脆又甜!咦,还有一位穿黄衣裳、弯弯像月牙的水果朋友在招手…是谁呀?' },
  { id: 22, emoji: '🍌', pinyin: 'xiāng jiāo', hanzi: '香蕉', english: 'banana', category: 'food', teaser: '香蕉甜甜的,厨房里还有一颗圆滚滚、壳硬硬、煮熟就变白的早餐朋友…是谁呀?' },
  { id: 23, emoji: '🥚', pinyin: 'jī dàn', hanzi: '鸡蛋', english: 'egg', category: 'food', teaser: '鸡蛋宝宝小声说:今天有位戴满奶油和蜡烛的伙伴过生日…它是谁呀?' },
  { id: 24, emoji: '🎂', pinyin: 'dàn gāo', hanzi: '蛋糕', english: 'cake', category: 'food', teaser: '奶油蛋糕分完啦,草地上冒出好多戴小伞的圆脑袋朋友…哪一个能吃呢?' },
  { id: 25, emoji: '🍄', pinyin: 'mó gu', hanzi: '蘑菇', english: 'mushroom', category: 'food', teaser: '采完小蘑菇,再往泥土里一拔,蹦出一根橙红色、脆甜脆甜的长条朋友…是谁呀?' },
  { id: 26, emoji: '🥕', pinyin: 'hú luó bo', hanzi: '胡萝卜', english: 'carrot', category: 'food', teaser: '小兔子说胡萝卜最棒,可太阳晒得热烘烘时,最想来座凉丝丝的甜雪山…是什么?' },
  { id: 27, emoji: '🍦', pinyin: 'bīng qí lín', hanzi: '冰淇淋', english: 'ice cream', category: 'food', teaser: '吃完冰淇淋,甜点柜里还有一位圆圆的、中间有个小洞洞的朋友等着你…是谁呀?' },
  { id: 28, emoji: '🍩', pinyin: 'tián tián quān', hanzi: '甜甜圈', english: 'donut', category: 'food', teaser: '甜甜圈吃完啦,再来颗圆滚滚、绿衣裳红肚皮、能解渴的大宝贝…是谁呀?' },
  { id: 29, emoji: '🍉', pinyin: 'xī guā', hanzi: '西瓜', english: 'watermelon', category: 'food', teaser: '西瓜好甜呀,果篮里那颗红红的小果子,顶着绿绿小帽子、浑身是小点点…是谁呀?' },
  { id: 30, emoji: '🍓', pinyin: 'cǎo méi', hanzi: '草莓', english: 'strawberry', category: 'food', teaser: '草莓酸酸甜甜,水果店还有位黄澄澄、像小水滴、一咬满口汁的朋友…是谁呀?' },
  { id: 31, emoji: '🍐', pinyin: 'lí', hanzi: '梨', english: 'pear', category: 'food', teaser: '梨儿脆脆的!咦,旁边那颗圆溜溜的小太阳,剥开是一瓣瓣小船…是谁呀?' },
  { id: 32, emoji: '🍊', pinyin: 'chéng zi', hanzi: '橙子', english: 'orange', category: 'food', teaser: '橙子剥好啦!盘子里还有一串穿紫袍、挤在一起咬耳朵的小圆珠…是谁呀?' },
  { id: 33, emoji: '🍇', pinyin: 'pú tao', hanzi: '葡萄', english: 'grape', category: 'food', teaser: '葡萄甜甜一嘟噜,口袋里又摸出几颗裹着亮亮糖纸的彩色宝石…是什么呀?' },
  { id: 34, emoji: '🍬', pinyin: 'táng guǒ', hanzi: '糖果', english: 'candy', category: 'food', teaser: '糖果有点太甜啦!换几块香喷喷、脆生生、印着小图案的圆片片…是谁呀?' },
  { id: 35, emoji: '🍪', pinyin: 'bǐng gān', hanzi: '饼干', english: 'cookie', category: 'food', teaser: '饼干咔嚓咔嚓!午饭时间到,一大块香喷喷、会拉丝的软圆饼来啦…是什么?' },
  { id: 36, emoji: '🍕', pinyin: 'bǐ sà', hanzi: '披萨', english: 'pizza', category: 'food', teaser: '披萨好香呀!烤箱里还住着一位鼓鼓胖胖、金黄喷香的早餐朋友…它在等谁?' },
  { id: 37, emoji: '🍞', pinyin: 'miàn bāo', hanzi: '面包', english: 'bread', category: 'food', teaser: '软软面包抹一抹,配上那位金灿灿、小老鼠最爱、还会拉丝的朋友…是谁呀?' },
  { id: 38, emoji: '🧀', pinyin: 'nǎi lào', hanzi: '奶酪', english: 'cheese', category: 'food', teaser: '奶酪咸咸香香,快喝一口亮晶晶、酸酸甜甜的果子水润润喉…是什么呀?' },
  { id: 39, emoji: '🧃', pinyin: 'guǒ zhī', hanzi: '果汁', english: 'juice', category: 'food', teaser: '果汁喝光光!早起还要一杯白白的、暖暖的,喝了能长高高的…是什么?' },
  { id: 40, emoji: '🥛', pinyin: 'niú nǎi', hanzi: '牛奶', english: 'milk', category: 'food', teaser: '牛奶香香的,谁家的小家伙闻着味儿,喵喵叫着一路跑来啦…是谁呀?' },
  // animal 41-60
  { id: 41, emoji: '🐱', pinyin: 'māo', hanzi: '猫', english: 'cat', category: 'animal', teaser: '猫猫的朋友总爱摇尾巴…是谁呀?' },
  { id: 42, emoji: '🐶', pinyin: 'gǒu', hanzi: '狗', english: 'dog', category: 'animal', teaser: '狗狗汪汪叫,草丛里「嗖」蹦出一位竖长耳朵、爱吃胡萝卜的害羞伙伴…是谁呀?' },
  { id: 43, emoji: '🐰', pinyin: 'tù zi', hanzi: '兔子', english: 'rabbit', category: 'animal', teaser: '小兔子蹦到池塘边,水里咕噜噜直冒泡…谁在摆着尾巴游来游去呀?' },
  { id: 44, emoji: '🐟', pinyin: 'yú', hanzi: '鱼', english: 'fish', category: 'animal', teaser: '小鱼儿游得欢!忽然扑棱一声,天上飞来一位会唱歌、有翅膀的朋友…它是谁?' },
  { id: 45, emoji: '🐦', pinyin: 'niǎo', hanzi: '鸟', english: 'bird', category: 'animal', teaser: '小鸟喳喳唱,墙脚小洞里传来细细的「吱吱」…谁在偷偷找饼干屑呀?' },
  { id: 46, emoji: '🐭', pinyin: 'lǎo shǔ', hanzi: '老鼠', english: 'mouse', category: 'animal', teaser: '小老鼠跑过池塘边,荷叶上「扑通」跳下一只绿衣裳、爱唱呱呱的朋友…是谁呀?' },
  { id: 47, emoji: '🐸', pinyin: 'qīng wā', hanzi: '青蛙', english: 'frog', category: 'animal', teaser: '青蛙呱呱叫!池塘边还有位背着硬壳小房子、走路慢吞吞的老朋友…是谁呀?' },
  { id: 48, emoji: '🐢', pinyin: 'wū guī', hanzi: '乌龟', english: 'turtle', category: 'animal', teaser: '乌龟慢慢爬呀爬,田野那头传来「哞——」…谁穿着黑白花衣裳,还会挤出白白的奶呀?' },
  { id: 49, emoji: '🐮', pinyin: 'nǎi niú', hanzi: '奶牛', english: 'cow', category: 'animal', teaser: '奶牛哞哞唱完歌,泥坑里那位圆滚滚、粉嘟嘟、爱打呼噜的朋友…是谁呀?' },
  { id: 50, emoji: '🐷', pinyin: 'zhū', hanzi: '猪', english: 'pig', category: 'animal', teaser: '小猪吃饱打呼噜,草地上那位裹着白云朵外衣、咩咩叫的朋友…是谁呀?' },
  { id: 51, emoji: '🐑', pinyin: 'mián yáng', hanzi: '绵羊', english: 'sheep', category: 'animal', teaser: '绵羊咩咩剪完毛!谷堆旁滚出一只毛茸茸、叽叽叫的黄色小球球…是谁呀?' },
  { id: 52, emoji: '🐤', pinyin: 'xiǎo jī', hanzi: '小鸡', english: 'chicken', category: 'animal', teaser: '小鸡叽叽找朋友,池塘里「嘎嘎」游来一位扁嘴巴、会游泳的伙伴…是谁呀?' },
  { id: 53, emoji: '🦆', pinyin: 'yā zi', hanzi: '鸭子', english: 'duck', category: 'animal', teaser: '鸭子嘎嘎上岸啦,远远传来「哒哒哒」…谁跑得飞快,鬃毛还在风里飘呀?' },
  { id: 54, emoji: '🐴', pinyin: 'mǎ', hanzi: '马', english: 'horse', category: 'animal', teaser: '小马跑过草原,远处传来一声震天吼…谁是顶着金色鬃毛的百兽之王呀?' },
  { id: 55, emoji: '🦁', pinyin: 'shī zi', hanzi: '狮子', english: 'lion', category: 'animal', teaser: '狮子吼一吼,大地都发抖…谁甩着长长的鼻子,是位个子最高的温柔大朋友?' },
  { id: 56, emoji: '🐘', pinyin: 'dà xiàng', hanzi: '大象', english: 'elephant', category: 'animal', teaser: '大象甩鼻子问好!树林里倒挂金钩、最爱挠痒痒和吃香蕉的小调皮…是谁呀?' },
  { id: 57, emoji: '🐵', pinyin: 'hóu zi', hanzi: '猴子', english: 'monkey', category: 'animal', teaser: '猴子摘完果子,咦,蜂蜜罐边守着一位爱吃甜、冬天爱睡大觉的大个子…是谁呀?' },
  { id: 58, emoji: '🐻', pinyin: 'xióng', hanzi: '熊', english: 'bear', category: 'animal', teaser: '大熊伸个懒腰,竹林里滚来一位黑白相间、抱着竹子啃的圆滚滚…它是谁呀?' },
  { id: 59, emoji: '🐼', pinyin: 'xióng māo', hanzi: '熊猫', english: 'panda', category: 'animal', teaser: '熊猫啃完竹子,森林深处慢慢探出条纹大衣、额头上像写「王」字的…是谁呀?' },
  { id: 60, emoji: '🐯', pinyin: 'lǎo hǔ', hanzi: '老虎', english: 'tiger', category: 'animal', teaser: '大老虎收起威风,山边一朵穿红衣裳、香喷喷的小精灵正朝它笑…是谁呀?' },
  // nature 61-80
  { id: 61, emoji: '🌸', pinyin: 'huā', hanzi: '花', english: 'flower', category: 'nature', teaser: '小花开了香香的!抬头看,身边站着一位又高又大、撑开绿色大伞的伙伴…是谁呀?' },
  { id: 62, emoji: '🌳', pinyin: 'shù', hanzi: '树', english: 'tree', category: 'nature', teaser: '大树沙沙摇!风一吹,好多绿绿的小巴掌轻轻朝你挥手…是什么呀?' },
  { id: 63, emoji: '🍃', pinyin: 'yè zi', hanzi: '叶子', english: 'leaf', category: 'nature', teaser: '叶子飘呀飘,落在地上…咦,谁给大地铺了一张绿绿的软毯子呀?' },
  { id: 64, emoji: '🌿', pinyin: 'cǎo', hanzi: '草', english: 'grass', category: 'nature', teaser: '小草喝饱了水,雨停啦!天边拱起一座七彩的滑滑梯…是谁来啦?' },
  { id: 65, emoji: '🌈', pinyin: 'cǎi hóng', hanzi: '彩虹', english: 'rainbow', category: 'nature', teaser: '彩虹桥收起啦,北风呼呼吹,天上飘下白白凉凉、亮晶晶的小六角…是什么呀?' },
  { id: 66, emoji: '❄️', pinyin: 'xuě huā', hanzi: '雪花', english: 'snowflake', category: 'nature', teaser: '雪花飘哇飘,咦,沙漠里站着一位满身小刺、很耐渴的绿色勇士…是谁呀?' },
  { id: 67, emoji: '🌵', pinyin: 'xiān rén zhǎng', hanzi: '仙人掌', english: 'cactus', category: 'nature', teaser: '仙人掌也开花了!花园里还有一位穿彩色裙子、开口像小杯子的花仙子…是谁呀?' },
  { id: 68, emoji: '🌷', pinyin: 'yù jīn xiāng', hanzi: '郁金香', english: 'tulip', category: 'nature', teaser: '郁金香轻轻弯腰,旁边那位圆脸小高个整天追着太阳转…它笑什么呀?' },
  { id: 69, emoji: '🌻', pinyin: 'xiàng rì kuí', hanzi: '向日葵', english: 'sunflower', category: 'nature', teaser: '向日葵笑呵呵!花圃边还有一位穿红裙子、藏着尖尖小刺、最香的娇小姐…是谁呀?' },
  { id: 70, emoji: '🌹', pinyin: 'méi gui', hanzi: '玫瑰', english: 'rose', category: 'nature', teaser: '玫瑰香又美!山坡上有位穿绿针衣、一年四季都青翠的老爷爷…它是谁呀?' },
  { id: 71, emoji: '🌲', pinyin: 'sōng shù', hanzi: '松树', english: 'pine tree', category: 'nature', teaser: '松树下也开花啦,嗡嗡嗡飞来一位勤劳的小园丁,忙着采花蜜…是谁呀?' },
  { id: 72, emoji: '🐝', pinyin: 'mì fēng', hanzi: '蜜蜂', english: 'bee', category: 'nature', teaser: '蜜蜂嗡嗡忙不停,花丛里还有一位穿花衣裳、跳舞不采蜜的小美人…是谁呀?' },
  { id: 73, emoji: '🦋', pinyin: 'hú dié', hanzi: '蝴蝶', english: 'butterfly', category: 'nature', teaser: '蝴蝶飞呀飞累了,树干上慢悠悠爬来一位背着小房子、拖银亮小路的朋友…是谁?' },
  { id: 74, emoji: '🐌', pinyin: 'wō niú', hanzi: '蜗牛', english: 'snail', category: 'nature', teaser: '蜗牛慢慢爬,叶片上静静落下一只红壳壳、背着七颗小黑豆的小飞机…是谁呀?' },
  { id: 75, emoji: '🐞', pinyin: 'piáo chóng', hanzi: '瓢虫', english: 'ladybug', category: 'nature', teaser: '小瓢虫拍拍翅膀飞走啦…咦,墙角那张闪闪发亮的网里,谁在等小飞虫呀?' },
  { id: 76, emoji: '🕷️', pinyin: 'zhī zhū', hanzi: '蜘蛛', english: 'spider', category: 'nature', teaser: '蜘蛛织好闪闪网,地上排成一队、扛着面包屑回家的黑色小工兵…是谁呀?' },
  { id: 77, emoji: '🐜', pinyin: 'mǎ yǐ', hanzi: '蚂蚁', english: 'ant', category: 'nature', teaser: '蚂蚁小小的,可能量满满!大海深处那位会喷水柱、比房子还大的温柔巨人…是谁呀?' },
  { id: 78, emoji: '🐳', pinyin: 'jīng yú', hanzi: '鲸鱼', english: 'whale', category: 'nature', teaser: '鲸鱼喷出小喷泉,浪花里跳出一位灰灰滑滑、最爱顶球和笑哈哈的…是谁呀?' },
  { id: 79, emoji: '🐬', pinyin: 'hǎi tún', hanzi: '海豚', english: 'dolphin', category: 'nature', teaser: '海豚玩得正开心,深海慢慢游来一位背鳍像小帆船、牙齿尖尖的…它是谁呀?' },
  { id: 80, emoji: '🦈', pinyin: 'shā yú', hanzi: '鲨鱼', english: 'shark', category: 'nature', teaser: '鲨鱼在海里游呀游…陆地上也有会跑、会「滴滴」叫的大家伙在等你…是什么呀?' },
  // object 81-100
  { id: 81, emoji: '🚗', pinyin: 'qì chē', hanzi: '汽车', english: 'car', category: 'object', teaser: '小汽车滴滴跑,大马路上还有一位又长又大、装下一整车乘客的蓝朋友…是谁呀?' },
  { id: 82, emoji: '🚌', pinyin: 'gōng jiāo chē', hanzi: '公交车', english: 'bus', category: 'object', teaser: '公交车到站啦!前方小河上摇摇晃晃,一位会载人的木头朋友靠岸啦…它是什么呀?' },
  { id: 83, emoji: '⛵', pinyin: 'xiǎo chuán', hanzi: '小船', english: 'boat', category: 'object', teaser: '小船儿划到河中央,抬头一看,云朵边有只大铁鸟「嗡嗡」飞过…是什么呀?' },
  { id: 84, emoji: '✈️', pinyin: 'fēi jī', hanzi: '飞机', english: 'plane', category: 'object', teaser: '飞机降落啦!站台上开来一列「呜呜呜」、一节接一节排长龙的朋友…是谁呀?' },
  { id: 85, emoji: '🚂', pinyin: 'huǒ chē', hanzi: '火车', english: 'train', category: 'object', teaser: '火车到终点啦!乡间小路上,一辆两个轮子、一蹬就呼呼跑的车…是什么呀?' },
  { id: 86, emoji: '🚲', pinyin: 'zì xíng chē', hanzi: '自行车', english: 'bicycle', category: 'object', teaser: '自行车骑呀骑…想飞上太空找星星,得请那位屁股喷火、直冲上天的大英雄…是谁呀?' },
  { id: 87, emoji: '🚀', pinyin: 'huǒ jiàn', hanzi: '火箭', english: 'rocket', category: 'object', teaser: '火箭咻地上天了!地上有位力气超大、专帮人运好多好多重东西的大家伙…是谁呀?' },
  { id: 88, emoji: '🚚', pinyin: 'kǎ chē', hanzi: '卡车', english: 'truck', category: 'object', teaser: '卡车卸完货啦!咦,家具堆里有一位等你坐下、靠着休息的四条腿好朋友…是谁呀?' },
  { id: 89, emoji: '🪑', pinyin: 'yǐ zi', hanzi: '椅子', english: 'chair', category: 'object', teaser: '坐稳小椅子,开饭啦!饭菜都摆在那张又大又平的木头好朋友身上…它叫什么呀?' },
  { id: 90, emoji: '🍽️', pinyin: 'zhuō zi', hanzi: '桌子', english: 'table', category: 'object', teaser: '桌子擦得干干净净,该睡觉啦…那块软软暖暖、能滚来滚去躺大觉的地方是哪儿呀?' },
  { id: 91, emoji: '🛏️', pinyin: 'chuáng', hanzi: '床', english: 'bed', category: 'object', teaser: '从暖暖的被窝钻出来,床头那位一响就亮、能跟远方家人说话的小方块…是谁呀?' },
  { id: 92, emoji: '📱', pinyin: 'shǒu jī', hanzi: '手机', english: 'phone', category: 'object', teaser: '手机放下啦!客厅里那位会走路、会说话、还会帮你做家务的铁皮朋友…是谁呀?' },
  { id: 93, emoji: '🤖', pinyin: 'jī qì rén', hanzi: '机器人', english: 'robot', category: 'object', teaser: '机器人带你去冒险!森林深处藏着一座尖尖塔楼、住着王子和公主的大房子…是什么呀?' },
  { id: 94, emoji: '🏰', pinyin: 'chéng bǎo', hanzi: '城堡', english: 'castle', category: 'object', teaser: '城堡开派对啦!天上飘着一只只圆鼓鼓、拉紧绳子想往上飞的彩色朋友…是谁呀?' },
  { id: 95, emoji: '🎈', pinyin: 'qì qiú', hanzi: '气球', english: 'balloon', category: 'object', teaser: '气球飞呀飞,看见国王头上戴着一顶亮闪闪、镶满宝石的圆帽子…它是谁呀?' },
  { id: 96, emoji: '👑', pinyin: 'wáng guān', hanzi: '皇冠', english: 'crown', category: 'object', teaser: '皇冠戴稳啦!小魔法师心里咕咚咕咚,装满暖暖的、像苹果一样红的东西…是什么呀?' },
  { id: 97, emoji: '❤️', pinyin: 'ài xīn', hanzi: '爱心', english: 'heart', category: 'object', teaser: '把爱心送给你!咦,生日派对上「呲」一声亮起小火苗、还会流眼泪的朋友…是谁呀?' },
  { id: 98, emoji: '🕯️', pinyin: 'là zhú', hanzi: '蜡烛', english: 'candle', category: 'object', teaser: '蜡烛暖洋洋,窗外那位白白胖胖、等你给它戴红围巾和胡萝卜鼻子的朋友…是谁呀?' },
  { id: 99, emoji: '⛄', pinyin: 'xuě rén', hanzi: '雪人', english: 'snowman', category: 'object', teaser: '雪人挥手说再见!传说天上还有一位鳞片闪闪、会喷火又会飞的神奇大朋友…是谁呀?' },
  { id: 100, emoji: '🐉', pinyin: 'lóng', hanzi: '龙', english: 'dragon', category: 'object', teaser: '骑上威武的大龙,一百颗星尘收齐啦!灵灵鼓掌:小魔法师真棒…还想再来冒险吗?' },
]

export function wordById(id: number): WordUnit | undefined {
  return WORDS.find((w) => w.id === id)
}
