// 服务契约统一出口。服务接口与同名 token 一体:普通导出同时带 type(接口)与 value(token),
// 因此消费者既可 `import type { ProgressService }` 仅作类型,也可 `import { ProgressService }`
// 作为注册/取用 key。纯数据/快照类型仍走 `export type`,不占 value 空间。
export type { Achievement, AchievementState } from './achievements'
export { AchievementService } from './achievements'
export type { ApiUserSettings, ApiWordProgress, User } from './api'
export { ApiService } from './api'
export type { AudioCue } from './audio'
export { AudioService } from './audio'
export type { AuthSnapshot } from './auth'
export { AuthService } from './auth'
export type { CelebrateLevel } from './celebrate'
export { CelebrateService } from './celebrate'
export type { AnswerKind, ComboSnapshot } from './combo'
export { ComboService } from './combo'
export { LuckyBonusService } from './lucky-bonus'
export type { ProgressData, ProgressSnapshot } from './progress'
export { ProgressService } from './progress'
export type { Rng } from './question-engine'
export { QuestionEngineService } from './question-engine'
export type { SettingsSnapshot } from './settings'
export { SettingsService } from './settings'
export { SpeechService } from './speech'
export type { ToastData, ToastType } from './toast'
export { ToastService } from './toast'
export { VocabularyService } from './vocabulary'
export type { LoadState } from '../load-state'
